pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=build (16.x)
      - status-success=netlify/traceurl/deploy-preview
      - status-success=security/gitguardian
    actions:
      merge:
        method: squash
      delete_head_branch:
