pull_request_rules:
  - name: automatic merge for owner pull requests
    conditions:
      - author=CatChen
      - "status-failure!=LGTM analysis: JavaScript"
      - status-success=netlify/traceurl/deploy-preview
      - status-success=security/gitguardian
    actions:
      merge:
        method: squash
      delete_head_branch:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - "status-failure!=LGTM analysis: JavaScript"
      - status-success=netlify/traceurl/deploy-preview
      - status-success=security/gitguardian
    actions:
      merge:
        method: squash
      delete_head_branch:
