pull_request_rules:
  - name: automatic merge for owner pull requests
    conditions:
      - author=CatChen
      - 'status-success=LGTM analysis: JavaScript'
      - status-success=continuous-integration/travis-ci/pr
      - status-success=netlify/traceurl/deploy-preview
      - status-success=security/gitguardian
    actions:
      merge:
        method: squash
      delete_head_branch:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot
      - 'status-success=LGTM analysis: JavaScript'
      - status-success=continuous-integration/travis-ci/pr
      - status-success=netlify/traceurl/deploy-preview
      - status-success=security/gitguardian
    actions:
      merge:
        method: squash
      delete_head_branch:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot
      - 'status-success=LGTM analysis: JavaScript'
      - status-neutral=continuous-integration/travis-ci/pr
      - status-success=netlify/traceurl/deploy-preview
      - status-success=security/gitguardian
    actions:
      merge:
        method: squash
      delete_head_branch:
